version: "3.8"

services:
  temperature-converter:
    image: nginx:alpine
    container_name: temperature-converter-js
    restart: unless-stopped
    ports:
      - "5002:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro